name: Perform Release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: Release Version
        required: true

jobs:
  maven-release:
    name: Maven Release
    runs-on: ubuntu-latest
    # Skip commit made by maven-release
    if: "!contains(github.event.head_commit.message, 'maven-release-plugin')"

    steps:
      - uses: actions/checkout@v2

      - name: Temporarily disable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
          access-token: ${{ secrets.BOT_GITHUB_REPO_ACCESS_TOKEN }}
          owner: igor-baiborodine
          enforce_admins: false
          repo: campsite-booking-test

      - name: Perform release
        uses: qcastel/github-actions-maven-release@master
        with:
          access-token: ${{ secrets.BOT_GITHUB_REPO_ACCESS_TOKEN }}
          git-release-bot-name: bot-campsite-booking
          git-release-bot-email: 'bot-campsite-booking@kiroule.com'
          maven-args: '-DskipTests -DskipITs'

      - name: Enable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
          access-token: ${{ secrets.BOT_GITHUB_REPO_ACCESS_TOKEN }}
          owner: igor-baiborodine
          repo: campsite-booking-test
