name: Perform Release
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: Release Version
        required: true
      snapshot_version:
        description: Snapshot Version
        required: true

jobs:
  maven-release:
    name: Maven Release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Versions Input
        run: echo "release version[${{ github.event.inputs.release_version }}], snapshot version[${{ github.event.inputs.snapshot_version }}]"
      - name: JDK 11 Set-up
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
