name: Perform Release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: Release Version
        required: true

jobs:
  maven-release:
    name: Maven Release
    runs-on: ubuntu-latest
    # Skip commit made by maven-release
    if: "!contains(github.event.head_commit.message, 'maven-release-plugin')"

    steps:
      - uses: actions/checkout@v2
      - name: Perform Release
        uses: qcastel/github-actions-maven-release@master
        with:
          git-release-bot-name: bot-campsite-booking
          git-release-bot-email: 'bot-campsite-booking@kiroule.com'
          access-token: ${{ secrets.GITHUB_TOKEN }}
          maven-args: '-DskipTests -DskipITs'
